### ISSUE TITLE
Fjerne questback-linken

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/tfk-form-skoleskyss#11]

**Comment by maccyber** [comment]
Fjerner du den?

Sammen med teksten:
Hjelp oss å bli bedre
Vi vil gjerne ha innspill til hvordan vi kan bli bedre.
Det hadde vært fint om du tok deg tid til å svare på en kort undersøkelse.
Den tar under 1 minutt :-)
Ta undersøkelsen

**Comment by zrrrzzt** [comment]
Jeg fjerner den i neste oppdatering ja
